# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with the specified version
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install the package and its dependencies
RUN pip install -e .

# Set environment variables
# Note: Replace 'your-openai-api-key' with your actual OpenAI API key or use a build argument or secret manager.
ENV OPENAI_API_KEY your-openai-api-key
ENV PYTHONPATH /app

# Command to run the MCP server
ENTRYPOINT ["python", "-m", "src.mcp_server_openai.server", "--openai-api-key", "your-openai-api-key"]
